<?php

function gallery_pager_block_info() {
  $blocks = array();
  // Provide a pager block that will work for all node types
  $blocks['gallery_pager'] = array(
    'info' => t('Gallery Pager (Before and After Gallery)'),
    'cache' => DRUPAL_NO_CACHE
  );
  return $blocks;
}

function gallery_pager_block_view($delta = '') {

  $block = array();
  switch ($delta) {
    case 'gallery_pager':
      $block['subject'] = '';
      $variables = array(); //do stuff here
      global $base_url;
   $query = db_select('draggableviews_structure', 'ds')
          ->fields('ds', array('args'))
          ->condition('view_name', 'b_a_gallery');
      $result = $query->distinct()->execute()->fetchAll();
      
      foreach($result as $values)
      {
        $args=$values->args;
        $args=  str_replace("[","",$args);
        $args=  str_replace("]","",$args);
        $args=  str_replace('"',"",$args);
        $check_args=explode(",",$args);    
        $args_list[]=$check_args;
      }
      $block['content'] = theme('gallery_pager', array('list'=>$args_list));
      break;
  }
  return $block;
}

function gallery_pager_theme() {
  return array(
    'gallery_pager' => array(
      'variables' => array(
        'list' => array(),
      ),
      'template' => 'gallery_pager',
    ),
  );
}

?>
