<?php

/**
 * This function defines the URL to the page created etc.
 * See http://api.drupal.org/api/function/hook_menu/6
 */
function formapi_menu() {
  //$items = array();
  $items['page1'] = array(
    'title' => "parent menu tabs",
   'page callback' => "formapi_php",
   // 'page arguments' => array(t('This is the "tabs" menu entry.')),
      'access callback' => 'user_access',
    	'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    
     );
  $items['page1/php'] = array(
    'title' => "php menu tabs",
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
    'access callback' => 'user_access',
    	'access arguments' => array('access content'),
    'page callback' => 'formapi_php',
  );

  $items['page1/java'] = array(
    'title' => "java menu tabs",
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'formapi_java',
    'access callback' => TRUE,
    'access arguments' => array('access content'),
    'weight' => 2,
  );
 
  return $items;
}

function formapi_kellton() {
 
  $var = "<h1>hiii kellton tech</h1>";
  return $var;
}

function formapi_php() {
  $var = "<h2>hiii php developers<h2>";
  return $var;
}

function formapi_java() {
  $var2 = "<h2>hiiii java developers<h2>";
  return $var2;
}
