<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function PreviousNext_menu()
{
  $items=array();
  $items['admin/config/system/previousnext']=array(
    'title'=>'PreviousNext',
  
    'page callback'=>'previousnext_list',
//   'page arguments' =>array('form_fun_form1'),
    'access callback'=>TRUE,
    'access_arguments'=>array('access content'),
    'file' =>'previousnext_code.inc',
      );
  return $items;
}

