<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function binfo_menu()
{
  $items=array();
  $items['btc']=array(
   'title'=>'block details',
    'page callback'=>'bretrieve',
    'access callback'=>TRUE,
    'access arguments'=>array('access content'),
    'file'=>'binfo_blocks.inc',
    'type'=>MENU_LOCAL_TASK,
    
    
  );
  $items['bbc']=array(
    'title'=>'page details',
    'page callback'=>'pshow',
    'access callback'=>TRUE,
    'access arguments'=>array('access content'),
    'file'=>'binfo2.inc',
    'type'=>MENU_LOCAL_TASK,
  );
  return$items;
}