<?php

/*
*implement hook _permission
*/
function blockdemo_permission()
{
return array(
'Namit demo module' => array(
'titile' => t("Namit Permission"),
'description' => t("perform adminsitrator tasks fot this module"),
    ),

 );
}
/* 
* Implements hook_node_view
*/
function blockdemo_node_view($node, $view_mode, $langcode){
//dsm("hiiiii");
$node->content['demo_field'] = array(
'#type' => 'markup',
'#markup' => '<p>'.t('this is a  Namit demo').'</p>',
//'#theme' => 'mymodule_my_additional_field',
'#weight' => -10,
);
$node->content['demo_list']=array(
'#items' => array('green','blue','red'),
'#theme' => 'item_list',
'#weight' => -9,

);
//if(user_access('administer'))
//{
//krumo($node);                                                                                    
//}
}