<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
function blog_category_fix_menu() {
    $items['admin/config/system/taxonomy-fix'] = array(
        'title' => 'Blog category fix',
        'page callback' => 'taxonomy_fix',
        'access arguments' => array('access contents'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'blog_category_fix.inc'
    );
return$items;
}
function blog_category_node_save($node)
{
    $nid=$node->nid;
    if($node->type == 'blog')
        {
$num_deleted = db_delete('taxonomy_index')
  ->condition('nid',$nid)
  ->execute();
   
        $category1=$node->field_category['und'];
        foreach($category1 as $tax_cat)
        {
                   
             $id = db_insert('taxonomy_index')->fields(array('nid' => $nid,'tid' => $tax_cat,'sticky'=>'0','created'=> time()))->execute();
        print_r($tax_cat);
             
        }
       
                        
        }
                 
               
        
}